### ISSUE TITLE
Duplicate Names

### ISSUE THREAD

**Issue by mjaworski-eab** [yargalot/gulp-accessibility#10]
If two html files in the same project have the same name the report for the files will be [](or possibly the last file).

Solution: You should construct a tree structure in the report folder or build one JSON

**Comment by yargalot** [comment]
Hey @jaworskm,

I've done that in the [yargalot/AccessSniff](https://github.com/yargalot/AccessSniff) 2.0 update, Just need to find the time to bring it across to this project. Should be this weekend by the latest.
