### ISSUE TITLE
Output to cli

### ISSUE THREAD

**Issue by lukasoppermann** [yargalot/gulp-accessibility#13]
Hey, can I instead of report to a file, just report to the cli? Did I miss this option?

**Comment by dahei** [comment]
@lukasoppermann 

Just use AccessSniff directly

https://github.com/yargalot/AccessSniff#cli

**Comment by JCron245** [comment]
```
gulp.task('wcag_test', function() {
  return gulp.src(html_paths)
    .pipe(access({
      force: true
    }))
    .on('error', console.log);
});
```

If you setup your gulp task like this it will **only** output to the CLI
